#!/bin/sh

# make sure router is running Entware and has an /opt/sbin directory

echo
echo
echo "mtd_check installer"
echo "This will install the mtd_check application to /opt/bin"
echo "and a small helper script (findmtd.sh) in /jffs/scripts"
echo -n "To continue, enter Y "
read a

if ! [ $a == "Y" -o $a == "y" ]; then
	echo "ok - exiting"
	exit
fi
echo
echo -n "Checking for Entware"
if ! [ -f /opt/bin/opkg ]; then
	echo "Entware not installed"
	echo "Can't install mtd_check..."
	exit
fi
echo " ok"
echo

# Check if an armv7l or aarch64 class router

echo "Checking for armv7l or aarch64 class kernel"
machtype=$(/bin/uname -m)
echo "Reported: " $machtype
echo

if [ $machtype == "armv7l" ]; then
	echo "Sorry, mtd_check only supports arm64 based routers..."
	exit 1
elif [ $machtype == "aarch64" ]; then
	echo "Installing mtd_check and its helper findmtd"
	/usr/sbin/curl --retry 3 "https://raw.githubusercontent.com/JGrana01/mtd_check/master/mtd_check" -o "/opt/sbin/mtd_check" && chmod 0755 "/opt/sbin/mtd_check"
	/usr/sbin/curl --retry 3 "https://raw.githubusercontent.com/JGrana01/mtd_check/master/findmtd.sh" -o "/jffs/scripts/findmtd.sh" && chmod 0755 "/jffs/scripts/findmtd.sh"
else
	echo "Sorry, mtd_check on runs on armv7l or aarch64 class routers"
	exit
fi

if [ -x /opt/bin/mtd_check ]; then
	echo
	echo "Installed mtd_check in /opt/bin"
	echo "Done"
else
	echo "Something went wrong, mtd_check not installed!!!"
fi

